import { useState } from 'react'
import { FileText, Download, CheckCircle } from 'lucide-react'

const REPORT_TEMPLATES = [
  {
    id: 'ip-health',
    title: 'IP Health Report',
    description: 'Full overview of all IP risks, conflicts, and prior art matches across patent, trademark, and prior art modules.',
    pages: '8–12 pages',
    sections: ['Executive summary', 'Patent similarity analysis', 'Trademark conflicts', 'Prior art findings', 'Risk score breakdown', 'Recommendations'],
  },
  {
    id: 'patent-only',
    title: 'Patent Risk Report',
    description: 'Focused analysis of patent similarity results and infringement risk for your specific technology domain.',
    pages: '4–6 pages',
    sections: ['Patent similarity matrix', 'Top 5 risk patents', 'Claim comparison', 'Domain landscape map'],
  },
  {
    id: 'trademark-only',
    title: 'Trademark Clearance Report',
    description: 'Brand name and logo similarity analysis across registered trademarks in your target markets.',
    pages: '3–5 pages',
    sections: ['Brand name analysis', 'Logo image comparison', 'Phonetic conflicts', 'Nice class coverage'],
  },
  {
    id: 'investor-brief',
    title: 'Investor IP Brief',
    description: 'One-page executive summary of IP posture designed for investor due diligence presentations.',
    pages: '1–2 pages',
    sections: ['IP portfolio summary', 'Key risks flagged', 'Mitigation steps', 'IP strategy roadmap'],
  },
]

const RECENT_REPORTS = [
  { title: 'IP Health Report — April 2025',   date: 'Apr 14, 2025', pages: 11, status: 'Ready' },
  { title: 'Patent Risk Report — March 2025', date: 'Mar 28, 2025', pages: 6,  status: 'Ready' },
  { title: 'Trademark Clearance — Q1 2025',   date: 'Mar 01, 2025', pages: 4,  status: 'Ready' },
]

function generateTextReport(template, startup) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const lines = [
    `${'='.repeat(60)}`,
    `${template.title.toUpperCase()}`,
    `${startup} · Generated ${now}`,
    `${'='.repeat(60)}`,
    '',
    'EXECUTIVE SUMMARY',
    '-'.repeat(40),
    `This report provides an AI-powered analysis of intellectual`,
    `property risks for ${startup}. The overall IP risk score`,
    `is 72/100 (HIGH), requiring immediate attention in the`,
    `patent and trademark categories.`,
    '',
    'KEY METRICS',
    '-'.repeat(40),
    '  Overall Risk Score   : 72 / 100 (HIGH)',
    '  Patents Analyzed     : 148',
    '  Trademark Conflicts  : 7 (2 high-risk)',
    '  Prior Art Matches    : 23',
    '',
    'TOP RISK ITEMS',
    '-'.repeat(40),
    '  1. US10234567 — Neural interface (Similarity: 91%) — HIGH',
    '     Assignee: DeepTech Corp · Filed: 2021',
    '',
    '  2. NovaMind logo — EU Trademark TM-2018-04421 (88%) — HIGH',
    '     Owner: NovaMind Technologies · Country: EU',
    '',
    '  3. EdgeSync brand name — 3 phonetic conflicts (74%) — MEDIUM',
    '     Class 42 (Technology & SaaS)',
    '',
    'RISK DIMENSIONS',
    '-'.repeat(40),
    '  Patent       : 85%  [HIGH]',
    '  Trademark    : 74%  [MEDIUM]',
    '  Prior Art    : 69%  [MEDIUM]',
    '  Geographic   : 55%  [MEDIUM]',
    '  Litigation   : 40%  [LOW]',
    '',
    'SECTIONS INCLUDED',
    '-'.repeat(40),
    ...template.sections.map(s => `  - ${s}`),
    '',
    'RECOMMENDATIONS',
    '-'.repeat(40),
    '  1. Consult a patent attorney regarding US10234567 overlap.',
    '  2. Rebrand or modify NovaMind logo before EU market entry.',
    '  3. File provisional patent for your core AI architecture.',
    '  4. Conduct freedom-to-operate (FTO) search in target markets.',
    '  5. Monitor EdgeSync trademark class 42 filings quarterly.',
    '',
    `${'='.repeat(60)}`,
    'Generated by IP Manager AI · Research Prototype',
    `Report ID: RPT-${Date.now().toString(36).toUpperCase()}`,
    `${'='.repeat(60)}`,
  ]
  return lines.join('\n')
}

export default function Reports() {
  const [generating, setGenerating] = useState(null)
  const [generated, setGenerated] = useState(null)
  const [startup, setStartup] = useState('TechNova AI')

  const handleGenerate = (template) => {
    setGenerating(template.id)
    setGenerated(null)
    setTimeout(() => {
      setGenerating(null)
      setGenerated(template.id)
    }, 1800)
  }

  const handleDownload = (template) => {
    const content = generateTextReport(template, startup)
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${template.id}-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fade-up">
      {/* Startup name input */}
      <div className="card mb-20">
        <div className="card-title">Report settings</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <label style={{ fontSize: 13, color: 'var(--text2)', flexShrink: 0 }}>Startup name:</label>
          <input
            type="text"
            value={startup}
            onChange={e => setStartup(e.target.value)}
            style={{ maxWidth: 280 }}
          />
        </div>
      </div>

      {/* Report templates */}
      <div style={{ marginBottom: 8, fontSize: 11, color: 'var(--text3)', letterSpacing: '0.08em', textTransform: 'uppercase', fontWeight: 500 }}>
        Report templates
      </div>
      <div className="grid-2 mb-20">
        {REPORT_TEMPLATES.map(tmpl => (
          <div key={tmpl.id} className="card" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 }}>
                <div style={{ fontWeight: 500, fontSize: 14 }}>{tmpl.title}</div>
                <span className="mono" style={{ fontSize: 11, color: 'var(--text3)' }}>{tmpl.pages}</span>
              </div>
              <p style={{ fontSize: 12, color: 'var(--text2)', lineHeight: 1.6, marginBottom: 10 }}>
                {tmpl.description}
              </p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>
                {tmpl.sections.map(s => (
                  <span key={s} style={{
                    fontSize: 11, padding: '2px 7px',
                    background: 'var(--bg3)',
                    border: '1px solid var(--border)',
                    borderRadius: 99,
                    color: 'var(--text3)',
                  }}>
                    {s}
                  </span>
                ))}
              </div>
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 'auto' }}>
              <button
                className="btn btn-primary"
                onClick={() => handleGenerate(tmpl)}
                disabled={generating === tmpl.id}
                style={{ flex: 1 }}
              >
                {generating === tmpl.id
                  ? <><span className="spinner" /> Generating...</>
                  : generated === tmpl.id
                    ? <><CheckCircle size={13} /> Generated</>
                    : <><FileText size={13} /> Generate</>
                }
              </button>
              {generated === tmpl.id && (
                <button
                  className="btn"
                  onClick={() => handleDownload(tmpl)}
                  title="Download report"
                >
                  <Download size={14} />
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Recent reports */}
      <div style={{ marginBottom: 8, fontSize: 11, color: 'var(--text3)', letterSpacing: '0.08em', textTransform: 'uppercase', fontWeight: 500 }}>
        Recent reports
      </div>
      <div className="card">
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Report name</th>
                <th>Generated</th>
                <th>Pages</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {RECENT_REPORTS.map((r, i) => (
                <tr key={i}>
                  <td style={{ fontWeight: 500, fontSize: 13 }}>{r.title}</td>
                  <td className="mono">{r.date}</td>
                  <td className="mono">{r.pages}</td>
                  <td>
                    <span className="pill pill-L">{r.status}</span>
                  </td>
                  <td>
                    <button
                      className="btn"
                      style={{ fontSize: 12, padding: '4px 10px' }}
                      onClick={() => {
                        const tmpl = REPORT_TEMPLATES[0]
                        handleDownload(tmpl)
                      }}
                    >
                      <Download size={12} /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
